%%% render module is responsible for rendering Markdown documents parsed
%%% by marker:marker function.
-module(render).
-include_lib("eunit/include/eunit.hrl").

-export([html/1]).

%% html renders markdown structure generated by marker:marker into
%% HTML string.
html(T)
    -> {ok, T}.

html_test() ->
    ?assertEqual({ok, [{par, "testpar"}]}, html([{par, "testpar"}])).
