%%% render module is responsible for rendering Markdown documents parsed
%%% by marker:marker function.
-module(render).
-include_lib("eunit/include/eunit.hrl").

-export([render/1]).

%% html renders markdown structure generated by marker:marker into
%% HTML string.
render(T)
    -> {ok, 
        html(T)
        }.

html([H|T]) -> html(H) ++ html(T);
html([]) -> "";
html({par, T})
    -> "<p>" ++ html(T) ++ "</p>";
html({normal, T})
    -> T.

html_test() ->
    ?assertEqual({ok, "regular text"}, render([{normal, "regular text"}])),
    ?assertEqual({ok, "<p>testpar</p>"}, render([{par, [{normal, "testpar"}]}])),
    ?assertEqual({ok, "<p>testpar</p><p>nextpar</p><p>thirdpar</p>"},
        render([{par, [{normal, "testpar"}]}, {par, [{normal, "nextpar"}]}, {par, [{normal, "thirdpar"}]}])).
